- name: Upgrade CentOS
  hosts: servers
  gather_facts: no
  tasks:
  - name: clean
    vars:
      ansible_port: "{{ PORT }}"
    command: yum clean all
  - name: upgrade all packages
    vars:
      ansible_port: "{{ PORT }}"
    yum:
      lock_timeout: 10
      name: '*'
      state: latest

  - name: check if reboot is required
    vars:
      ansible_port: "{{ PORT }}"
    shell: needs-restarting -r
    failed_when: false
    register: reboot_required
    changed_when: false

  - when: reboot_required.rc != 0
    block:
      - name: reboot the server if required
        vars:
          ansible_port: "{{ PORT }}"
        shell: sleep 3; reboot
        ignore_errors: true
        changed_when: false
        async: 1
        poll: 0
      - name: wait for server to come back after reboot
        vars:
          ansible_port: "{{ PORT }}"
        wait_for_connection:
          timeout: 600
          delay: 20
        register: reboot_result
      - name: reboot time
        vars:
          ansible_port: "{{ PORT }}"
        debug:
          msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."